spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # in production -> none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
